events {}

http {

    upstream backend {
        server app1:8081;
        server app2:8081;
        server app3:8081 backup;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}